### ISSUE TITLE
创建新的资源，日志显示不是最新

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/RMC#5]
显示的日志应该是反映目前正在安装的状态，达到及时了解情况的目的。
但实际显示出来的日志，一直停留在一开始创建的时间点上，往下拉滚动条想看下最新，结果自动移到最上端。看不到安装过程中的日志。

**Comment by sunhongzhen** [comment]
更新日志的时候，滚动条总是自动跳到最上端

**Comment by yuanman** [comment]
日志信息是通过orderId获取的，如果每次测试不更换orderId，会取到老的日志信息。

**Comment by sunhongzhen** [comment]
取到老的日志没问题，问题是：滚动条能不能定位到最下面，已能看到最新的日志，这是目的。
